apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "quarkus-native"
  description: "quarkus native app"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/quarkus
  consumesApis: 
    - openapi-skeleton